
const translations = {
    "Add Service": { es: "Agregar Servicio", en: "Add Service" },
    "Add New Service": { es: "Agregar Nuevo Servicio", en: "Add New Service" },
    "Name of Service": { es: "Nombre del servicio", en: "Name of Service" },
    "Description of the Service": { es: "Descripción del servicio", en: "Description of the Service" },
    "Total Service": { es: "Total del Servicio", en: "Total Service" },
    "Service Image": { es: "Imagen del Servicio", en: "Service Image" },
    "Close": { es: "Cerrar", en: "Close" },
    "Edit Service": { es: "Editar Servicio", en: "Edit Service" },
    "Edit": { es: "Editar", en: "Edit" },
    "Delete": { es: "Eliminar", en: "Delete" },
    "No services registered.": { es: "No hay servicios registrados.", en: "No services registered." },
    "Manage Services": { es: "Administrar Servicios", en: "Manage Services" },
    "Good Morning": { es: "Buenos días", en: "Good Morning" },
    "Good Afternoon": { es: "Buenas tardes", en: "Good Afternoon" },
    "Good Night": { es: "Buenas noches", en: "Good Night" },
    "Log In": { es: "Iniciar sesión", en: "Log In" },
    "Customers": { es: "Clientes", en: "Customers" },
    "Employee": { es: "Empleado", en: "Employee" },
    "Company": { es: "Empresas", en: "Company" },
    "Works": { es: "Obras", en: "Works" },
    "Budget": { es: "Presupuesto", en: "Budget" },
    "Employee Payroll": { es: "Nómina de Empleados", en: "Employee Payroll" },
    "Actions": { es: "Acciones", en: "Actions" },
    "Home": { es: "Inicio", en: "Home" },
    "Manage Customers": { es: "Administrar Clientes", en: "Manage Customers" },
    "Add Customer": { es: "Agregar Cliente", en: "Add Customer" },
    "View Addresses": { es: "Ver Direcciones", en: "View Addresses" },
    "Status": { es: "Estatus", en: "Status" },
    "Role": { es: "Rol", en: "Role" },
    "Age": { es: "Edad", en: "Age" },
    "Email": { es: "Correo Electrónico", en: "Email" },
    "Phone": { es: "Teléfono", en: "Phone" },
    "Gender": { es: "Género", en: "Gender" },
    "Customer Name": { es: "Nombre del Cliente", en: "Customer Name" },
    "Edit Customer": { es: "Editar Cliente", en: "Edit Customer" },
    "Save Changes": { es: "Guardar Cambios", en: "Save Changes" },
    "Add Customer Address": { es: "Añadir Dirección del Cliente", en: "Add Customer Address" },
    "Paternal Surname": { es: "Apellido Paterno", en: "Paternal Surname" },
    "Maternal Surname": { es: "Apellido Materno", en: "Maternal Surname" },
    "Outside Number": { es: "Número Exterior", en: "Outside Number" },
    "Inner Number": { es: "Número Interior", en: "Inner Number" },
    "Street": { es: "Calle", en: "Street" },
    "City": { es: "Ciudad", en: "City" },
    "State": { es: "Estado", en: "State" },
    "Postal Code": { es: "Código Postal", en: "Postal Code" },
    "Deactivate Customer": { es: "Desactivar Cliente", en: "Deactivate Customer" },
    "Activate Customer": { es: "Activar Cliente", en: "Activate Customer" },
    "Delete Customer": { es: "Eliminar Cliente", en: "Delete Customer" },
    "Add Address": { es: "Agregar Dirección", en: "Add Address" },
    "Password": { es: "Contraseña", en: "Password" },
    "Confirm Password": { es: "Confirmar Contraseña", en: "Confirm Password" },
    "Customer": { es: "Cliente", en: "Customer" },
    "Edit Customer Address": { es: "Editar Dirección del Cliente", en: "Edit Customer Address" },
    "Manage Customers Addresses": { es: "Administrar Direcciones de Clientes", en: "Manage Customers Addresses" },
    "Back": { es: "Regresar", en: "Back" },
    "Add New Customer": { es: "Agregar Nuevo Cliente", en: "Add New Customer" },
    "Current Image": { es: "Imágen Actual", en: "Current Image" },
    "Update Service Image": { es: "Actualizar imágen del Servicio", en: "Update Service Image" },
    "Manage Employee": { es: "Administrar Empleados", en: "Manage Employee" },
    "Position": { es: "Cargo", en: "Position" },
    "Activities": { es: "Actividades", en: "Activities" },
    "Days Worked": { es: "Días Trabajados", en: "Days Worked" },
    "Exit Time": { es: "Hora Salida", en: "Exit Time" },
    "Entry Time": { es: "Hora Entrada", en: "Entry Time" },
    "Employee Name": { es: "Nombre de Empleado", en: "Employee Name" },
    "Selected a Company": { es: "Selecciona una Empresa", en: "Selected a Company" },
    "Edit Employee": { es: "Editar Empleado", en: "Edit Employee" },
    "Selected Days Worked": { es: "Seleccionar Días Trabajados", en: "Selected Days Worked" },
    "Monday": { es: "Lunes", en: "Monday" },
    "Tuesday": { es: "Martes", en: "Tuesday" },
    "Wednesday": { es: "Miércoles", en: "Wednesday" },
    "Thursday": { es: "Jueves", en: "Thursday" },
    "Friday": { es: "Viernes", en: "Friday" },
    "Saturday": { es: "Sábado", en: "Saturday" },
    "Sunday": { es: "Domingo", en: "Sunday" },
    "Add Company": { es: "Agregar Empresa", en: "Add Company" },
    "Web Page": { es: "Página web", en: "Web Page" },
    "Company Name": { es: "Nombre de la Empresa", en: "Company Name" },
    "Add Company Address": { es: "Añadir Dirección de la Empresa", en: "Add Company Address" },
    "Manage Company": { es: "Administrar Empresas", en: "Manage Company" },
    "Selected Company": { es: "Empresa Seleccionada", en: "Selected Company" },
    "Manage Company Addresses": { es: "Administrar Direcciones de Empresas", en: "Manage Company Addresses" },
    "Edit Company Address": { es: "Editar Dirección de Empresa", en: "Edit Company Address" },
    "Add Work": { es: "Agregar Obra", en: "Add Work" },
    "Manage Works": { es: "Administrar Obras", en: "Manage Works" },
    "Observations": { es: "Observaciones", en: "Observations" },
    "Total Work": { es: "Total de la Obra", en: "Total Work" },
    "Debit": { es: "Adeudo", en: "Debit" },
    "Advance Payment": { es: "Anticipo", en: "Advance Payment" },
    "Start Date": { es: "Fecha Inicio", en: "Start Date" },
    "Customer Address": { es: "Dirección del Cliente", en: "Customer Address" },
    "Work ID": { es: "ID Obra", en: "Work ID" },
    "Edit Work Address": { es: "Editar Dirección de Obra", en: "Edit Work Address" },
    "Manage Works Addresses": { es: "Administrar Direcciones de Obras", en: "Manage Works Addresses" },
    "Add New Work": { es: "Agregar Nueva Obra", en: "Add New Work" },
    "Selected a Customer": { es: "Selecciona un Cliente", en: "Selected a Customer" },
    "Edit Work": { es: "Editar Obra", en: "Edit Work" },
    "Add Budget": { es: "Agregar Presupuesto", en: "Add Budget" },
    "Manage Budgets": { es: "Administrar Presupuestos", en: "Manage Budgets" },
    "Date of Preparation": { es: "Fecha de Elaboración", en: "Date of Preparation" },
    "Edit Budget Address": { es: "Editar Dirección de Presupuesto", en: "Edit Budget Address" },
    "Manage Budget Addresses": { es: "Administrar Direcciones de Presupuestos", en: "Manage Budget Addresses" },
    "Add New Budget": { es: "Agregar Nuevo Presupuesto", en: "Add New Budget" },
    "Edit Budget": { es: "Editar Presupuesto", en: "Edit Budget" },
    "Add Budget Address": { es: "Añadir Dirección del Presupuesto", en: "Add Budget Address" },
    "Selected Budget": { es: "Presupuesto Seleccionado", en: "Selected Budget" },
    "Add Work Address": { es: "Añadir Dirección de la Obra", en: "Add Work Address" },
    "Date": { es: "Fecha", en: "Date" },
    "Add Payroll": { es: "Agregar Nómina", en: "Add Payroll" },
    "Manage Payrolls": { es: "Administrar Nóminas", en: "Manage Payrolls" },
    "Daily Salary": { es: "Sueldo Diario", en: "Daily Salary" },
    "Add New Payroll": { es: "Agregar Nueva Nómina", en: "Add New Payroll" },
    "Selected a Employee": { es: "Selecciona un Empleado", en: "Selected a Employee" },
    "Edit Payroll": { es: "Editar Nómina", en: "Edit Payroll" },
    "Welcome Admin": { es: "Bienvenido Administrador", en: "Welcome Admin" },
    "Learn More": { es: "Aprender más", en: "Learn More" },
    "© Family Drywall. All rights reserved": { es: "© Family Drywall. Todos los Derechos reservados", en: "© Family Drywall. All rights reserved" },
    "Discover our services and offerings": { es: "Descubra nuestros servicios y ofertas", en: "Discover our services and offerings" },
    "Profile": { es: "Perfil", en: "Profile" },
    "Services": { es: "Servicios", en: "Services" },
    "Contact": { es: "Contacto", en: "Contact" },
    "Customers": { es: "Clientes", en: "Customers" },
    "Employee": { es: "Empleado", en: "Employee" },
    "Works": { es: "Obras", en: "Works" },
    "Budget": { es: "Presupuesto", en: "Budget" },
    "Employee Payroll": { es: "Nómina de empleados", en: "Employee Payroll" },
    "Change Language": { es: "Cambiar idioma", en: "Change Language" },
    "Change Theme": { es: "Cambiar tema", en: "Change Theme" },
    "Welcome Employee": { es: "Bienvenido Empleado", en: "Welcome Employee" },
    "Welcome to Our Website": { es: "Bienvenido a nuestro sitio web", en: "Welcome to Our Website" },
    "Our Services": { es: "Nuestros Servicios", en: "Our Services" },
    "Generate PDF": { es: "Generar PDF", en: "Generate PDF" },
    "Delete Work": { es: "Eliminar Obra", en: "Delete Work" },
    "Service Name": { es: "Nombre del Servicio", en: "Service Name" },
    "Manage Services Category": { es: "Administrar Categorias de los Servicios", en: "Manage Services Category" },
    "Name of Category": { es: "Nombre de la categoría", en: "Name of Category" },
    "Height": { es: "Altura", en: "Height" },
    "Add Service Category": { es: "Agregar Categoría de Servicio", en: "Add Service Category" },
    "Edit Service Category": { es: "Editar Categoría de Servicio", en: "Edit Service Category" },
    "Service Category": { es: "Categoría de Servicio", en: "Service Category" },
    "Add Employee": { es: "Agregar Empleado", en: "Add Employee" },
    "Search Payroll": { es: "Buscar Nóminas", en: "Search Payroll" },
    "Select Employee": { es: "Seleccionar Empleado", en: "Select Employee" },
    "Search by:": { es: "Buscar por:", en: "Search by:" },
    "Month": { es: "Mes", en: "Month" },
    "Week": { es: "Semana", en: "Week" },
    "Select Date:": { es: "Seleccionar Fecha", en: "Select Date:" },
    "Search": { es: "Buscar", en: "Search" },
    "Select Week:": { es: "Seleccionar Semana", en: "Select Week:" },
    "Week 1": { es: "Semana 1", en: "Week 1" },
    "Week 2": { es: "Semana 2", en: "Week 2" },
    "Week 3": { es: "Semana 3", en: "Week 3" },
    "Week 4": { es: "Semana 4", en: "Week 4" },
    "Please perform a search to see payroll results.": { es: "Por favor, realiza una búsqueda para ver los resultados de la nómina.", en: "Please perform a search to see payroll results." },
    "There are no payrolls recorded.": { es: "No hay nóminas registradas.", en: "There are no payrolls recorded." },
    "There are no works recorded.": { es: "No hay obras registradas.", en: "There are no works recorded." },
    "There are no budgets recorded.": { es: "No hay presupuestos registrados.", en: "There are no budgets recorded." },
    "There are no customers recorded.": { es: "No hay clientes registrados.", en: "There are no customers recorded." },
    "There are no company recorded.": { es: "No hay empresas registradas.", en: "There are no company recorded." },
    "There are no company address recorded.": { es: "No hay direcciones de empresas registradas.", en: "There are no company address recorded." },
    "There are no employees recorded.": { es: "No hay empleados registrados.", en: "There are no employees recorded." },
    "There are no services recorded.": { es: "No hay servicios registrados.", en: "There are no services recorded." },
    "There are no service categories recorded.": { es: "No hay categorías de servicios registradas.", en: "There are no service categories recorded." },
    "There are no budget addresses recorded.": { es: "No hay direcciones de presupuestos registradas.", en: "There are no budget addresses recorded." },
    "There are no work addresses recorded.": { es: "No hay direcciones de obras registradas.", en: "There are no work addresses recorded." },
    "There are no payroll addresses recorded.": { es: "No hay direcciones de nóminas registradas.", en: "There are no payroll addresses recorded." },
    "There are no customers addresses recorded.": { es: "No hay direcciones de clientes registradas.", en: "There are no customers addresses recorded." },
    "Are you sure you want to delete this work?": { es: "¿Estás seguro de que deseas eliminar esta obra?", en: "Are you sure you want to delete this work?" },
    "Send PDF": { es: "Enviar PDF", en: "Send PDF" },
    "Work Status": { es: "Estado de Obra", en: "Work Status" },
    "Complete": { es: "Completa", en: "Complete" },
    "Medium": { es: "En Progreso", en: "Medium" },
    "Initial": { es: "Iniciada", en: "Initial" },
    "Change Work Status": { es: "Cambiar Estado de Obra", en: "Change Work Status" },
    "View PDF": { es: "Ver PDF", en: "View PDF" },
    "Service": { es: "Servicio", en: "Service" },
    "Edit Company": { es: "Editar Empresa", en: "Edit Company" },
    "Delete Work" : { es: "Eliminar Obra", en: "Delete Work" },
    "Delete Company" : {es: "Eliminar Empresa", en: "Delete Company"},
    "Delete Customer" : {es: "Eliminar Cliente", en: "Delete Customer"},
    "Delete Employee" : {es: "Eliminar Empleado", en: "Delete Employee"},
    "Delete Service Category" : {es: "Eliminar Categoría de Servicio", en: "Delete Service Category"},
    "Delete Budget" : {es: "Eliminar Presupuesto", en: "Delete Budget"},
    "Delete Work Address" : {es: "Eliminar Dirección de Obra", en: "Delete Work Address"},
    "Delete Payroll Address" : {es: "Eliminar Dirección de Nómina", en: "Delete Payroll Address"},
    "Delete Budget Address" : {es: "Eliminar Dirección de Presupuesto", en: "Delete Budget Address"},
    "Delete Customer Address" : {es: "Eliminar Dirección de Cliente", en: "Delete Customer Address"},
    "Delete Service" : {es: "Eliminar Servicio", en: "Delete Service"},
    "Deactivate Employee" : {es: "Desactivar Empleado", en: "Deactivate Employee"},
    "Activate Employee" : {es: "Activar Empleado", en: "Activate Employee"},
    "Payrolls" : {es: "Nóminas", en: "Payrolls"},
    "log out" : {es: "Cerrar Sesión", en: "log out"},
    "Upload" : {es: "Cargar", en: "Upload"},
    "Upload Signature" : {es: "Cargar Firma", en: "Upload Signature"},
    "Personal Data" : {es: "Datos Personales", en: "Personal Data"},
    "Name" : {es: "Nombre", en: "Name"},
    "Last Name" : {es: "Apellidos", en: "Last Name"},
    "Address" : {es: "Dirección", en: "Address"},
    "Add Address" : {es: "Agregar Dirección", en: "Add Address"},
    "The address data was not found." : {es: "No se encontraron datos de dirección.", en: "The address data was not found."},
    "Qoute" : {es: "Cotizar", en: "Qoute"},
    "You don't have a registered address. Please enter an address to proceed with the quotation." : {es: "No tienes una dirección registrada. Por favor, ingresa una dirección para continuar con la cotización.", en: "You don't have a registered address. Please enter an address to proceed with the quotation."},
    "Do you want to add a new address?" : {es: "¿Deseas agregar una nueva dirección?", en: "Do you want to add a new address?"},
    "Do you want to keep this address or add a new one?" : {es: "¿Deseas conservar esta dirección o agregar una nueva?", en: "Do you want to keep this address or add a new one?"},
    "Keep current address" : {es: "Conservar dirección actual", en: "Keep current address"},
    "Current address:" : {es: "Dirección Actual", en: "Current address:"},
    "Add New Address" : {es: "Agregar Nueva Dirección", en: "Add New Address"},
    "Signature File:" : {es: "Archivo de Firma", en: "Signature File:"},

};


function translatePage() {
    document.querySelectorAll("*").forEach(element => {
        if (element.children.length === 0 && element.innerText.trim()) {
            const text = element.innerText.trim();
            if (isSpanish && translations[text]) {
                element.innerText = translations[text].es;
            } else if (!isSpanish) {
                element.innerText = translations[text] ? translations[text].en : text;
            }
        }

        if (element.hasAttribute("title")) {
            const titleText = element.getAttribute("title").trim();
            if (isSpanish && translations[titleText]) {
                element.setAttribute("title", translations[titleText].es);
            } else if (!isSpanish) {
                element.setAttribute("title", translations[titleText] ? translations[titleText].en : titleText);
            }
        }
    });
}

let isSpanish = localStorage.getItem("language") === "es";

function toggleLanguage() {
    isSpanish = !isSpanish;
    localStorage.setItem("language", isSpanish ? "es" : "en");
    translatePage();
}

document.addEventListener("DOMContentLoaded", () => {
    translatePage();
    document.getElementById("languageButton").addEventListener("click", toggleLanguage);
});
